<?php if($this->advertiser != null): ?>
<dl id="advertiser">
<?php foreach($this->advertiser as $field=>$value): ?>
	<dt id="advertiserDetailsField-<?php print $field; ?>" class='advertiserDetailsField'><?php print $field; ?></dt>
	<dd><?php print $value; ?></dd>
<?php endforeach; ?>
<dt id='updateDetailsLink'><a href="/advertiser/update">Update details</a></dt>
</dl>
<?php endif; ?>
<table id="adverts">
<tr>
<th>Title</th>
<th>Url</th>
<th>Click Count</th>
<th>  </th>
</tr>
<?php foreach($this->adverts as $advert): ?>
	<tr class="advertDetails">
		<td><?php print $advert->title; ?></td>
		<td><?php print $advert->url; ?></td>
		<td><?php print $advert->history[0]->clickCount; ?></td>
		<td><a href='advert/remove/<?php print $advert->advertID; ?>'>update</a></td>
	</tr>
<?php endforeach; ?>
</table>