<script src='/js/jquery-1.3.2.js'></script>
<h1 id='timer' style="margin:0px;padding:0px;float:left;"><?php print $this->interval; ?></h1>
<img id='status' src="/images/blank.jpg" style="float:right;margin:0px;padding:0px;" height="50px" width="50px"/>
<br style="clear:both">

<script>
timerID = setInterval('countdown()', 1000);
function countdown() {
	var current = $('#timer').text();
	if(current == 0) {
		clearInterval(timerID);
		$.get('/advert/view/check', setStatus);
	}
	else {
		$('#timer').text(current - 1);
	}
}
function setStatus(status) {
	$('#status').attr('src', '/images/'+status+'.jpg');
}
</script>
<iframe src="<?php print $this->advert->url; ?>" width="100%" height="100%" frameborder='0'/>